version: '3'

services:
  test-unit:
    build: .
    volumes:
      - ./:/code
    working_dir: /code
    command: /bin/bash -l ./tests/run_tests_unit.sh

  coverage:
    build: .
    volumes:
      - ./:/code
    working_dir: /code
    command: /bin/bash -l ./tests/run_code_coverage.sh