name: Build and run tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMG: 'teristam/ephys_ms3:20220302'
    steps:
      - uses: actions/checkout@v1
      - name: Configure environment
        run: |
          sudo fallocate -l 3G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon -s

          mkdir artifacts

      # - name: Build Docker image
      #   run: |
      #     # export PREBUILT_IMAGE=docker.io/4iar/ephys_ms3
      #     # docker pull $PREBUILT_IMAGE || true
      #     # docker build --cache-from $PREBUILT_IMAGE . -t ephys

      - name: Run unit tests
        run: |
          docker run -t -v ${PWD}:/code -w /code $DOCKER_IMG /bin/bash -l ./tests/run_tests_unit.sh

      - name: Run integration tests
        run: |
          docker run -t -v ${PWD}:/home/nolanlab/PycharmProjects/in_vivo_ephys_openephys -w /home/nolanlab/PycharmProjects/in_vivo_ephys_openephys $DOCKER_IMG /bin/bash -l ./tests/run_tests_integration.sh

      - name: Prepare results data for upload
        run: |
          zip -P ${{ secrets.ARTIFACT_PASSWORD }} -r artifacts.zip artifacts

      - uses: actions/upload-artifact@master
        with:
          name: data
          path: artifacts.zip
          retention-days: 1

      - name: Run code coverage
        run: |
          docker run -v ${PWD}:/code -w /code $DOCKER_IMG /bin/bash -l ./tests/run_code_coverage.sh ${{ secrets.CODECOV_TOKEN }} ${{ github.sha }}
